{
 "title": "DeepDetect Prometheus Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DeepDetect instances UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "instances" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (dd_available)" }
   ]
  },
  {
   "title": "DeepDetect instances DOWN",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "instances" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dd_available) - count(dd_available)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (rate(deepdetect_predict_duration_seconds_total[5m])/rate(deepdetect_predict_requests_total[5m]))",
     "legendFormat": "[{{ml_type}}] {{service_name}}"
    }
   ]
  },
  {
   "title": "Average inference time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (rate(deepdetect_predict_duration_seconds_total[5m])/rate(deepdetect_predict_requests_total[5m]))-avg (rate(deepdetect_transform_duration_seconds_total[5m])/rate(deepdetect_predict_requests_total[5m]))",
     "legendFormat": "[{{ml_type}}] {{service_name}}"
    }
   ]
  },
  {
   "title": "Average inference time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (rate(deepdetect_transform_duration_seconds_total[5m])/rate(deepdetect_predict_requests_total[5m]))",
     "legendFormat": "[{{ml_type}}] {{service_name}}"
    }
   ]
  },
  {
   "title": "DeepDetect versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (dd_version)(dd_available)"
    }
   ]
  },
  {
   "title": "DeepDetect commit ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (dd_commit)(dd_available)"
    }
   ]
  },
  {
   "title": "Loaded services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "services" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (service_name)(deepdetect_predict_duration_seconds_total))"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests per service ( stacked )",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name, ml_type)(rate(deepdetect_predict_requests_total[5m]))",
     "legendFormat": "[{{ml_type}}] {{service_name}}"
    }
   ]
  },
  {
   "title": "Average response time per service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (service_name, ml_type)(rate(deepdetect_predict_duration_seconds_total[5m])/rate(deepdetect_predict_requests_total[5m]))",
     "legendFormat": "[{{ml_type}}] {{service_name}}"
    }
   ]
  },
  {
   "title": "Average batch size per service",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (service_name,ml_type)(deepdetect_batch_size_avg)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Average inference time per service",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (service_name,ml_type)(\n  avg by (service_name,ml_type)\n     (rate(deepdetect_predict_duration_seconds_total[5m])/rate(deepdetect_predict_requests_total[5m]))\n  - avg by (service_name,ml_type)\n     (rate(deepdetect_transform_duration_seconds_total[5m])/rate(deepdetect_predict_requests_total[5m]))\n     )",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Average transform time per service",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (service_name,ml_type)\n     (rate(deepdetect_transform_duration_seconds_total[5m])/rate(deepdetect_predict_requests_total[5m]))\n     ",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Failed requests per service",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name)(rate(deepdetect_predict_requests_failure_total[5m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}